services:
  - type: web
    name: farm-analytics-dashboard
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r App/requirements.txt

    startCommand: streamlit run App/Dashboard.py --server.port=$PORT --server.address=0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

build:
  python:
    usePoetry: false