services:
  - type: web
    name: farm-analytics-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Dashboard.py --server.port=$PORT --server.address=0.0.0.0
    rootDir: Farm_Analytics/App
